// This file is kept for type compatibility only.
// All real data is loaded from backend APIs via donor-store.ts refreshDashboard / refreshDocuments etc.
import type { DonorData } from "./donor-schemas";

export const initialData: DonorData = {
  currentPoints: 1250,
  stats: [],
  recentActivities: [],
  donationHistory: [
    {
      id: "DON-1001",
      foodType: "Cooking Oil Canisters",
      category: "Dry Ration",
      dietaryType: "Veg",
      preparationType: "Packaged",
      quantity: "5 Litres",
      donor: "Star Hotel",
      date: "Jun 23, 2026",
      expiryTime: "Jun 23, 2026, 7:00 PM",
      status: "PENDING",
      pickupAddress: "Star Hotel Main Lobby, Block 4, Sector 7, MG Road",
      description: "Fresh unopened cooking oil canisters for donation.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 23, 2026",
          time: "06:00 PM",
          completed: true,
          description: "Food donation request created. Waiting for NGO acceptance.",
        },
      ],
    },
    {
      id: "DON-1007",
      foodType: "Whole Wheat Atta Bags",
      category: "Dry Ration",
      dietaryType: "Veg",
      preparationType: "Packaged",
      quantity: "25 kg",
      donor: "Star Hotel",
      date: "Jun 23, 2026",
      expiryTime: "Jun 23, 2026, 8:00 PM",
      status: "PENDING",
      pickupAddress: "Star Hotel Central Store, Room 102",
      description: "Sealed whole wheat flour bags ready for distribution.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 23, 2026",
          time: "07:00 PM",
          completed: true,
          description: "Food donation request created. Waiting for NGO acceptance.",
        },
      ],
    },
    {
      id: "DON-1002",
      foodType: "Basmati Rice Bags",
      category: "Dry Ration",
      dietaryType: "Veg",
      preparationType: "Packaged",
      quantity: "50 kg",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 24, 2026",
      expiryTime: "Jun 24, 2026, 8:30 PM",
      status: "ACCEPTED",
      pickupAddress: "Star Hotel Main Kitchen Loading Dock",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Basmati rice bags (2 bags of 25kg each). Stored in a cool dry place.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 24, 2026",
          time: "10:00 AM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 24, 2026",
          time: "11:30 AM",
          completed: true,
          description: "NGO Helping Hands accepted the request.",
        },
      ],
    },
    {
      id: "DON-1008",
      foodType: "Fresh Milk & Dairy Trays",
      category: "Dry Ration",
      dietaryType: "Veg",
      preparationType: "Packaged",
      quantity: "30 Litres",
      ngo: "Youth Care Foundation",
      donor: "Star Hotel",
      date: "Jun 24, 2026",
      expiryTime: "Jun 24, 2026, 9:00 PM",
      status: "ACCEPTED",
      pickupAddress: "Star Hotel Kitchen Chiller Room",
      deliveryAddress: "Youth Care Shelter, MG Road Branch",
      description: "Chilled fresh milk trays packed in thermal container boxes.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 24, 2026",
          time: "11:00 AM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 24, 2026",
          time: "12:00 PM",
          completed: true,
          description: "NGO Youth Care Foundation accepted the request.",
        },
      ],
    },
    {
      id: "DON-1003",
      foodType: "Fresh Tomatoes & Potatoes",
      category: "Fresh Produce",
      dietaryType: "Veg",
      preparationType: "Raw",
      quantity: "15 kg",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 25, 2026",
      expiryTime: "Jun 25, 2026, 6:00 PM",
      status: "ASSIGNED",
      pickupAddress: "Star Hotel Rear Entrance, Gate 2",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Fresh farm vegetables harvested yesterday, kept in clean crates.",
      volunteer: {
        name: "John V",
        phone: "+91 98765 43210",
        rating: "4.8",
      },
      volunteerLocation: { lat: 12.9716, lng: 77.5946 },
      pickupCoords: { lat: 12.9722, lng: 77.595 },
      deliveryCoords: { lat: 12.9698, lng: 77.593 },
      timeline: [
        {
          status: "Pending",
          date: "Jun 25, 2026",
          time: "02:00 PM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 25, 2026",
          time: "02:15 PM",
          completed: true,
          description: "NGO accepted the request.",
        },
        {
          status: "Assigned",
          date: "Jun 25, 2026",
          time: "02:30 PM",
          completed: true,
          description: "Volunteer John V assigned for pickup.",
        },
      ],
    },
    {
      id: "DON-1009",
      foodType: "Mixed Fruit Baskets",
      category: "Fresh Produce",
      dietaryType: "Veg",
      preparationType: "Raw",
      quantity: "25 kg",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 25, 2026",
      expiryTime: "Jun 25, 2026, 7:30 PM",
      status: "ASSIGNED",
      pickupAddress: "Star Hotel Front Desk Lobby",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Assorted fresh seasonal fruit baskets for children shelter.",
      volunteer: {
        name: "Sarah M",
        phone: "+91 98765 11223",
        rating: "4.9",
      },
      volunteerLocation: { lat: 12.972, lng: 77.594 },
      pickupCoords: { lat: 12.9722, lng: 77.595 },
      deliveryCoords: { lat: 12.9698, lng: 77.593 },
      timeline: [
        {
          status: "Pending",
          date: "Jun 25, 2026",
          time: "03:00 PM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 25, 2026",
          time: "03:15 PM",
          completed: true,
          description: "NGO accepted the request.",
        },
        {
          status: "Assigned",
          date: "Jun 25, 2026",
          time: "03:30 PM",
          completed: true,
          description: "Volunteer Sarah M assigned for pickup.",
        },
      ],
    },
    {
      id: "DON-1004",
      foodType: "Vegetable Biryani Meals",
      category: "Cooked Food",
      dietaryType: "Veg",
      preparationType: "Restaurant",
      quantity: "30 Meals",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 26, 2026",
      expiryTime: "Jun 26, 2026, 9:00 PM",
      status: "PICKED_UP",
      pickupAddress: "Star Hotel Buffet Area, Ground Floor",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Delicious hot vegetable biryani meals packed in eco-friendly containers.",
      volunteer: {
        name: "John V",
        phone: "+91 98765 43210",
        rating: "4.8",
      },
      volunteerLocation: { lat: 12.9702, lng: 77.5938 },
      pickupCoords: { lat: 12.9722, lng: 77.595 },
      deliveryCoords: { lat: 12.9698, lng: 77.593 },
      timeline: [
        {
          status: "Pending",
          date: "Jun 26, 2026",
          time: "12:00 PM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 26, 2026",
          time: "12:10 PM",
          completed: true,
          description: "NGO accepted the request.",
        },
        {
          status: "Assigned",
          date: "Jun 26, 2026",
          time: "12:15 PM",
          completed: true,
          description: "Volunteer John V assigned.",
        },
        {
          status: "Picked Up",
          date: "Jun 26, 2026",
          time: "12:35 PM",
          completed: true,
          description: "Volunteer picked up food. In transit to shelter.",
        },
      ],
    },
    {
      id: "DON-1010",
      foodType: "Paneer Butter Masala Packs",
      category: "Cooked Food",
      dietaryType: "Veg",
      preparationType: "Restaurant",
      quantity: "40 Meals",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 26, 2026",
      expiryTime: "Jun 26, 2026, 9:30 PM",
      status: "PICKED_UP",
      pickupAddress: "Star Hotel Kitchen Counter",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Freshly cooked paneer butter masala with Indian breads.",
      volunteer: {
        name: "Alex R",
        phone: "+91 98765 99887",
        rating: "4.7",
      },
      volunteerLocation: { lat: 12.9708, lng: 77.5942 },
      pickupCoords: { lat: 12.9722, lng: 77.595 },
      deliveryCoords: { lat: 12.9698, lng: 77.593 },
      timeline: [
        {
          status: "Pending",
          date: "Jun 26, 2026",
          time: "01:00 PM",
          completed: true,
          description: "Food donation request created.",
        },
        {
          status: "Accepted",
          date: "Jun 26, 2026",
          time: "01:10 PM",
          completed: true,
          description: "NGO accepted the request.",
        },
        {
          status: "Assigned",
          date: "Jun 26, 2026",
          time: "01:15 PM",
          completed: true,
          description: "Volunteer Alex R assigned.",
        },
        {
          status: "Picked Up",
          date: "Jun 26, 2026",
          time: "01:40 PM",
          completed: true,
          description: "Volunteer picked up food parcel.",
        },
      ],
    },
    {
      id: "DON-1005",
      foodType: "Fresh Apples & Oranges Box",
      category: "Fresh Produce",
      dietaryType: "Veg",
      preparationType: "Raw",
      quantity: "20 kg",
      ngo: "Helping Hands NGO",
      donor: "Star Hotel",
      date: "Jun 20, 2026",
      expiryTime: "Jun 20, 2026, 6:25 PM",
      status: "DELIVERED",
      pickupAddress: "Star Hotel Main Entrance Pantry",
      deliveryAddress: "Helping Hands Shelter, Sector 2, Lane B",
      description: "Fresh selected fruits box for kids.",
      volunteer: {
        name: "John V",
        phone: "+91 98765 43210",
        rating: "4.8",
      },
      timeline: [
        {
          status: "Pending",
          date: "Jun 20, 2026",
          time: "09:00 AM",
          completed: true,
        },
        {
          status: "Accepted",
          date: "Jun 20, 2026",
          time: "09:15 AM",
          completed: true,
        },
        {
          status: "Assigned",
          date: "Jun 20, 2026",
          time: "09:30 AM",
          completed: true,
        },
        {
          status: "Picked Up",
          date: "Jun 20, 2026",
          time: "09:50 AM",
          completed: true,
        },
        {
          status: "Delivered",
          date: "Jun 20, 2026",
          time: "10:15 AM",
          completed: true,
          description: "Donation successfully delivered to NGO shelter. Thank you!",
        },
      ],
    },
    {
      id: "DON-1011",
      foodType: "Assorted Sandwich Platters",
      category: "Cooked Food",
      dietaryType: "Veg",
      preparationType: "Restaurant",
      quantity: "50 Items",
      ngo: "Community Care Shelter",
      donor: "Star Hotel",
      date: "Jun 19, 2026",
      expiryTime: "Jun 19, 2026, 8:00 PM",
      status: "DELIVERED",
      pickupAddress: "Star Hotel Conference Hall Pantry",
      deliveryAddress: "Community Care Shelter, Block C",
      description: "Fresh vegetable grilled sandwich platters.",
      volunteer: {
        name: "Sarah M",
        phone: "+91 98765 11223",
        rating: "4.9",
      },
      timeline: [
        {
          status: "Pending",
          date: "Jun 19, 2026",
          time: "04:00 PM",
          completed: true,
        },
        {
          status: "Accepted",
          date: "Jun 19, 2026",
          time: "04:20 PM",
          completed: true,
        },
        {
          status: "Assigned",
          date: "Jun 19, 2026",
          time: "04:35 PM",
          completed: true,
        },
        {
          status: "Picked Up",
          date: "Jun 19, 2026",
          time: "05:00 PM",
          completed: true,
        },
        {
          status: "Delivered",
          date: "Jun 19, 2026",
          time: "05:40 PM",
          completed: true,
          description: "Delivered successfully.",
        },
      ],
    },
    {
      id: "DON-1006",
      foodType: "Pasteurized Milk Packets",
      category: "Dry Ration",
      dietaryType: "Veg",
      preparationType: "Packaged",
      quantity: "40 Packets",
      donor: "Star Hotel",
      date: "Jun 21, 2026",
      expiryTime: "Jun 21, 2026, 5:00 PM",
      status: "CANCELLED",
      pickupAddress: "Star Hotel Main Pantry Fridge 2",
      description: "Pasteurized milk packets. Cancelled due to storage issues.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 21, 2026",
          time: "08:00 AM",
          completed: true,
        },
        {
          status: "Cancelled",
          date: "Jun 21, 2026",
          time: "09:00 AM",
          completed: true,
          description: "Donation request cancelled by donor.",
        },
      ],
    },
    {
      id: "DON-1012",
      foodType: "Surplus Banquet Salad Boxes",
      category: "Fresh Produce",
      dietaryType: "Veg",
      preparationType: "Raw",
      quantity: "15 kg",
      donor: "Star Hotel",
      date: "Jun 22, 2026",
      expiryTime: "Jun 22, 2026, 6:00 PM",
      status: "CANCELLED",
      pickupAddress: "Star Hotel Banquet Pantry",
      description: "Cancelled surplus salad boxes due to transport delay.",
      timeline: [
        {
          status: "Pending",
          date: "Jun 22, 2026",
          time: "10:00 AM",
          completed: true,
        },
        {
          status: "Cancelled",
          date: "Jun 22, 2026",
          time: "11:00 AM",
          completed: true,
          description: "Cancelled by donor.",
        },
      ],
    },
  ],
  profile: {
    businessName: "Star Hotel",
    businessType: "Restaurant",
    registrationId: "REG-884920",
    taxId: "TAX-99201",
    name: "John Manager",
    email: "starhotel@hungerfree.org",
    phone: "+91 98765 00000",
    location: "Bangalore",
    memberSince: "2024",
    verificationLevel: "Verified",
    completion: 100,
    bankName: null,
    accountNumber: null,
    upiId: null,
    branch: null,
    legalName: "Star Hotel Pvt Ltd",
    website: "https://starhotel.com",
    entityType: "Private Limited",
    alternateContact: "+91 98765 00001",
    address: { line1: "MG Road", city: "Bangalore", state: "Karnataka", postalCode: "560001", country: "India" }
  },
  documents: [],
  prizes: [],
  rewards: [],
  bankAccounts: [],
  upiIds: []
};


